# Generated by Django 4.0.1 on 2022-01-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('nutrient_id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrient_name', models.CharField(max_length=150)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'nutrient',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductJs',
            fields=[
                ('product_js_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_js', models.TextField()),
                ('source', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'product_js',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('parent_id', models.IntegerField()),
                ('parent_multiplier', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='ProductStruct',
            fields=[
                ('product_struct_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.IntegerField()),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='berg.nutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='berg.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='berg.unit')),
            ],
            options={
                'db_table': 'product_struct',
            },
        ),
    ]
